<?php

namespace Proxies\__CG__\Modules\AuthenticateBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Papeis extends \Modules\AuthenticateBundle\Entity\Papeis implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setDsIdentificador($dsIdentificador)
    {
        $this->__load();
        return parent::setDsIdentificador($dsIdentificador);
    }

    public function getDsIdentificador()
    {
        $this->__load();
        return parent::getDsIdentificador();
    }

    public function setDtCriacao($dtCriacao)
    {
        $this->__load();
        return parent::setDtCriacao($dtCriacao);
    }

    public function getDtCriacao()
    {
        $this->__load();
        return parent::getDtCriacao();
    }

    public function setIdPapel($idPapel)
    {
        $this->__load();
        return parent::setIdPapel($idPapel);
    }

    public function getIdPapel()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idPapel"];
        }
        $this->__load();
        return parent::getIdPapel();
    }

    public function setNoPapel($noPapel)
    {
        $this->__load();
        return parent::setNoPapel($noPapel);
    }

    public function getNoPapel()
    {
        $this->__load();
        return parent::getNoPapel();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idPapel', 'noPapel', 'dsIdentificador', 'dtCriacao');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}