modules_authentication:
    resource: "@ModulesAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /
    options:
            expose: true

modules_user:
    resource: "@ModulesUserBundle/Resources/config/routing.yml"
    prefix:   /
    options:
            expose: true

modules_layout:
    resource: "@ModulesLayoutBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
