security:
    acl:
        connection: default
    encoders:
        Modules\AuthenticationBundle\Entity\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        users:
            entity: { class: ModulesAuthenticationBundle:User, property: login}

    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false

            secured_area:
                pattern:    ^/
                anonymous: true
                form_login:
                    login_path:  /login
                    check_path:  /login_check

                logout:
                    path:   /logout
                    target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

