security:
    encoders:
        Modules\AuthenticateBundle\Entity\Usuario:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        users:
            entity: { class: ModulesAuthenticateBundle:Usuario, property: login}

    firewalls:
            secured_area:
                pattern:    ^/
                anonymous: ~
                form_login:
                    login_path:  /login
                    check_path:  /login_check
                    default_target_path: /internal

    access_control:
        - { path: ^/internal, roles: ROLE_ADMIN }

