#parameters:
#    modules.user.user.class: Modules\UsuarioBundle\Services\User
#
#services:
#    modules_usuario.usuario.service:
#        class: %modules_usuario.usuario.class%
#        arguments: ["@service_container","@doctrine.orm.entity_manager"]