parameters:
    modules.user.user.class: Modules\UserBundle\Services\User

services:
    modules_user.user.service:
        class: %modules_user.user.class%
        arguments: ["@service_container","@doctrine.orm.entity_manager"]