login_path:
    pattern:  /login
    defaults: { _controller: ModulesAuthenticationBundle:Authentication:login }

login_check:
    pattern:  /login_check
    defaults: { _controller: ModulesAuthenticationBundle:Authentication:loginCheck }

path:
    pattern:  /logout
    defaults: { _controller: ModulesAuthenticationBundle:Authentication:logout }